from enum import Enum
class Role(str, Enum): ADMIN="ADMIN"; AFFILIATE="AFFILIATE"; SALES="SALES"; FINANCE="FINANCE"; STAFF="STAFF"
class ApplicationStatus(str, Enum): PENDING="PENDING"; APPROVED="APPROVED"; ACTIVE="ACTIVE"; REJECTED="REJECTED"; ON_HOLD="ON_HOLD"
class LeadStatus(str, Enum): NEW="NEW"; CONTACTED="CONTACTED"; CONNECTED="CONNECTED"; QUALIFIED="QUALIFIED"; UNQUALIFIED="UNQUALIFIED"; COUNSELLING="COUNSELLING"; ENROLLED="ENROLLED"; LOST="LOST"
class CounsellingStatus(str, Enum): SCHEDULED="SCHEDULED"; CONTACTED="CONTACTED"; COMPLETED="COMPLETED"; NO_SHOW="NO_SHOW"; RESCHEDULED="RESCHEDULED"; CANCELLED="CANCELLED"
class EnrollmentStatus(str, Enum): PENDING="PENDING"; CONFIRMED="CONFIRMED"; CANCELLED="CANCELLED"; REFUNDED="REFUNDED"; COMPLETED="COMPLETED"
class CommissionStatus(str, Enum): PENDING="PENDING"; UNDER_REVIEW="UNDER_REVIEW"; APPROVED="APPROVED"; REJECTED="REJECTED"; PAID="PAID"; REVERSED="REVERSED"
class PayoutStatus(str, Enum): PENDING="PENDING"; VALIDATING="VALIDATING"; APPROVED="APPROVED"; PROCESSING="PROCESSING"; PAID="PAID"; FAILED="FAILED"; CANCELLED="CANCELLED"
class EventType(str, Enum): PAGE_VIEW="PAGE_VIEW"; CTA_CLICK="CTA_CLICK"; APPLICATION_STARTED="APPLICATION_STARTED"; APPLICATION_COMPLETED="APPLICATION_COMPLETED"; APPLICATION_APPROVED="APPLICATION_APPROVED"; AFFILIATE_ACTIVATED="AFFILIATE_ACTIVATED"; REFERRAL_CLICK="REFERRAL_CLICK"; LANDING_PAGE_VISIT="LANDING_PAGE_VISIT"; LEAD_SUBMITTED="LEAD_SUBMITTED"; LEAD_CONNECTED="LEAD_CONNECTED"; LEAD_QUALIFIED="LEAD_QUALIFIED"; COUNSELLING_SCHEDULED="COUNSELLING_SCHEDULED"; COUNSELLING_COMPLETED="COUNSELLING_COMPLETED"; ENROLLMENT="ENROLLMENT"; COMMISSION_CREATED="COMMISSION_CREATED"; COMMISSION_APPROVED="COMMISSION_APPROVED"; COMMISSION_PAID="COMMISSION_PAID"
