from fastapi import APIRouter, Depends
from sqlalchemy.orm import Session
from ...core.database import get_db
from ...core.exceptions import BusinessError
from ...models import AffiliateLink, TrackingEvent, EventType
from ...schemas.tracking import TrackingEventCreate
from ...utils.json import dumps
router=APIRouter(prefix="/tracking",tags=["Tracking"])
PUBLIC_EVENTS={EventType.PAGE_VIEW,EventType.CTA_CLICK,EventType.APPLICATION_STARTED,EventType.APPLICATION_COMPLETED,EventType.LANDING_PAGE_VISIT}
@router.post("/event")
def event(payload:TrackingEventCreate,db:Session=Depends(get_db)):
    try: et=EventType(payload.event_type)
    except ValueError: raise BusinessError("VALIDATION_ERROR","Unsupported tracking event.",422)
    if et not in PUBLIC_EVENTS: raise BusinessError("FORBIDDEN","This event can only be generated by trusted backend services.",403)
    affiliate_id=None
    if payload.referral_code:
        link=db.query(AffiliateLink).filter(AffiliateLink.referral_code==payload.referral_code,AffiliateLink.active.is_(True)).first()
        if link: affiliate_id=link.affiliate_id
    db.add(TrackingEvent(event_type=et,affiliate_id=affiliate_id,session_id=payload.session_id,entity_id=payload.entity_id,metadata_json=dumps(payload.metadata))); db.commit()
    return {"success":True,"message":"Event recorded."}
