"""initial affiliate platform schema

Revision ID: 550032697b3d
Revises: 
Create Date: 2026-09-08 06:57:23.656561
"""
from typing import Sequence, Union
from alembic import op
import sqlalchemy as sa


revision: str = '550032697b3d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('campaigns',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('code', sa.String(length=80), nullable=False),
    sa.Column('start_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('end_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_campaigns_code'), 'campaigns', ['code'], unique=True)
    op.create_index(op.f('ix_campaigns_public_id'), 'campaigns', ['public_id'], unique=True)
    op.create_table('courses',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('slug', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('price', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_courses_public_id'), 'courses', ['public_id'], unique=True)
    op.create_index(op.f('ix_courses_slug'), 'courses', ['slug'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('role', sa.Enum('ADMIN', 'AFFILIATE', 'SALES', 'FINANCE', 'STAFF', name='role', native_enum=False), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_verified', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_index(op.f('ix_users_public_id'), 'users', ['public_id'], unique=True)
    op.create_index(op.f('ix_users_role'), 'users', ['role'], unique=False)
    op.create_table('affiliate_applications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('instagram', sa.String(length=500), nullable=True),
    sa.Column('youtube', sa.String(length=500), nullable=True),
    sa.Column('linkedin', sa.String(length=500), nullable=True),
    sa.Column('website', sa.String(length=500), nullable=True),
    sa.Column('audience_size', sa.String(length=80), nullable=True),
    sa.Column('social_media_followers', sa.String(length=80), nullable=True),
    sa.Column('content_category', sa.String(length=160), nullable=True),
    sa.Column('platforms', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=False),
    sa.Column('target_audience', sa.Text(), nullable=False),
    sa.Column('audience_type', sa.String(length=160), nullable=True),
    sa.Column('audience_location', sa.String(length=160), nullable=False),
    sa.Column('main_platform', sa.String(length=80), nullable=False),
    sa.Column('average_reach', sa.String(length=80), nullable=True),
    sa.Column('affiliate_experience', sa.String(length=10), nullable=False),
    sa.Column('previous_experience', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ACTIVE', 'REJECTED', 'ON_HOLD', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('review_notes', sa.Text(), nullable=True),
    sa.Column('reviewed_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['reviewed_by'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_applications_email'), 'affiliate_applications', ['email'], unique=False)
    op.create_index(op.f('ix_affiliate_applications_phone'), 'affiliate_applications', ['phone'], unique=False)
    op.create_index(op.f('ix_affiliate_applications_public_id'), 'affiliate_applications', ['public_id'], unique=True)
    op.create_index(op.f('ix_affiliate_applications_status'), 'affiliate_applications', ['status'], unique=False)
    op.create_table('affiliates',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('affiliate_id', sa.String(length=32), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPROVED', 'ACTIVE', 'REJECTED', 'ON_HOLD', name='applicationstatus', native_enum=False), nullable=False),
    sa.Column('category', sa.String(length=160), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliates_affiliate_id'), 'affiliates', ['affiliate_id'], unique=True)
    op.create_index(op.f('ix_affiliates_public_id'), 'affiliates', ['public_id'], unique=True)
    op.create_index(op.f('ix_affiliates_status'), 'affiliates', ['status'], unique=False)
    op.create_index(op.f('ix_affiliates_user_id'), 'affiliates', ['user_id'], unique=True)
    op.create_table('audit_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('actor_user_id', sa.Integer(), nullable=True),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('entity_type', sa.String(length=120), nullable=False),
    sa.Column('entity_id', sa.String(length=120), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_user_id'), 'audit_logs', ['actor_user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_id'), 'audit_logs', ['entity_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_entity_type'), 'audit_logs', ['entity_type'], unique=False)
    op.create_table('commission_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('percentage', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('fixed_amount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('effective_from', sa.DateTime(timezone=True), nullable=True),
    sa.Column('effective_until', sa.DateTime(timezone=True), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('priority', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commission_rules_campaign_id'), 'commission_rules', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_commission_rules_course_id'), 'commission_rules', ['course_id'], unique=False)
    op.create_index(op.f('ix_commission_rules_public_id'), 'commission_rules', ['public_id'], unique=True)
    op.create_table('content_assets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('asset_type', sa.String(length=80), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_content_assets_campaign_id'), 'content_assets', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_content_assets_public_id'), 'content_assets', ['public_id'], unique=True)
    op.create_table('notifications',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('title', sa.String(length=200), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('notification_type', sa.String(length=80), nullable=False),
    sa.Column('read_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_notifications_user_id'), 'notifications', ['user_id'], unique=False)
    op.create_table('affiliate_links',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('referral_code', sa.String(length=80), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=True),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_affiliate_links_affiliate_id'), 'affiliate_links', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_campaign_id'), 'affiliate_links', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_course_id'), 'affiliate_links', ['course_id'], unique=False)
    op.create_index(op.f('ix_affiliate_links_public_id'), 'affiliate_links', ['public_id'], unique=True)
    op.create_index(op.f('ix_affiliate_links_referral_code'), 'affiliate_links', ['referral_code'], unique=True)
    op.create_table('payouts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'VALIDATING', 'APPROVED', 'PROCESSING', 'PAID', 'FAILED', 'CANCELLED', name='payoutstatus', native_enum=False), nullable=False),
    sa.Column('period_start', sa.DateTime(timezone=True), nullable=True),
    sa.Column('period_end', sa.DateTime(timezone=True), nullable=True),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('transaction_reference', sa.String(length=160), nullable=True),
    sa.Column('failure_reason', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('transaction_reference')
    )
    op.create_index(op.f('ix_payouts_affiliate_id'), 'payouts', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_payouts_public_id'), 'payouts', ['public_id'], unique=True)
    op.create_index(op.f('ix_payouts_status'), 'payouts', ['status'], unique=False)
    op.create_table('performance_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('event_type', sa.Enum('PAGE_VIEW', 'CTA_CLICK', 'APPLICATION_STARTED', 'APPLICATION_COMPLETED', 'APPLICATION_APPROVED', 'AFFILIATE_ACTIVATED', 'REFERRAL_CLICK', 'LANDING_PAGE_VISIT', 'LEAD_SUBMITTED', 'LEAD_CONNECTED', 'LEAD_QUALIFIED', 'COUNSELLING_SCHEDULED', 'COUNSELLING_COMPLETED', 'ENROLLMENT', 'COMMISSION_CREATED', 'COMMISSION_APPROVED', 'COMMISSION_PAID', name='eventtype', native_enum=False), nullable=False),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('occurred_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_performance_events_affiliate_id'), 'performance_events', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_performance_events_event_type'), 'performance_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_performance_events_occurred_at'), 'performance_events', ['occurred_at'], unique=False)
    op.create_table('referrals',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_link_id', sa.Integer(), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=False),
    sa.Column('landing_path', sa.String(length=500), nullable=True),
    sa.Column('referrer', sa.String(length=500), nullable=True),
    sa.Column('utm_source', sa.String(length=200), nullable=True),
    sa.Column('utm_medium', sa.String(length=200), nullable=True),
    sa.Column('utm_campaign', sa.String(length=200), nullable=True),
    sa.Column('first_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('last_seen_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['affiliate_link_id'], ['affiliate_links.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_referrals_affiliate_id'), 'referrals', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_referrals_affiliate_link_id'), 'referrals', ['affiliate_link_id'], unique=False)
    op.create_index('ix_referrals_affiliate_session', 'referrals', ['affiliate_id', 'session_id'], unique=False)
    op.create_index(op.f('ix_referrals_public_id'), 'referrals', ['public_id'], unique=True)
    op.create_index(op.f('ix_referrals_session_id'), 'referrals', ['session_id'], unique=False)
    op.create_table('leads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('phone', sa.String(length=40), nullable=False),
    sa.Column('email', sa.String(length=320), nullable=False),
    sa.Column('course_interest', sa.String(length=200), nullable=True),
    sa.Column('student_professional_status', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=160), nullable=True),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('source', sa.String(length=80), nullable=False),
    sa.Column('status', sa.Enum('NEW', 'CONTACTED', 'CONNECTED', 'QUALIFIED', 'UNQUALIFIED', 'COUNSELLING', 'ENROLLED', 'LOST', name='leadstatus', native_enum=False), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_leads_affiliate_created', 'leads', ['affiliate_id', 'created_at'], unique=False)
    op.create_index(op.f('ix_leads_affiliate_id'), 'leads', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_leads_campaign_id'), 'leads', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_leads_email'), 'leads', ['email'], unique=False)
    op.create_index(op.f('ix_leads_phone'), 'leads', ['phone'], unique=False)
    op.create_index(op.f('ix_leads_public_id'), 'leads', ['public_id'], unique=True)
    op.create_index(op.f('ix_leads_referral_id'), 'leads', ['referral_id'], unique=False)
    op.create_index(op.f('ix_leads_status'), 'leads', ['status'], unique=False)
    op.create_table('tracking_events',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('PAGE_VIEW', 'CTA_CLICK', 'APPLICATION_STARTED', 'APPLICATION_COMPLETED', 'APPLICATION_APPROVED', 'AFFILIATE_ACTIVATED', 'REFERRAL_CLICK', 'LANDING_PAGE_VISIT', 'LEAD_SUBMITTED', 'LEAD_CONNECTED', 'LEAD_QUALIFIED', 'COUNSELLING_SCHEDULED', 'COUNSELLING_COMPLETED', 'ENROLLMENT', 'COMMISSION_CREATED', 'COMMISSION_APPROVED', 'COMMISSION_PAID', name='eventtype', native_enum=False), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('referral_id', sa.Integer(), nullable=True),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('entity_id', sa.String(length=100), nullable=True),
    sa.Column('metadata_json', sa.Text(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['referral_id'], ['referrals.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_tracking_event_type_created', 'tracking_events', ['event_type', 'created_at'], unique=False)
    op.create_index(op.f('ix_tracking_events_affiliate_id'), 'tracking_events', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_event_type'), 'tracking_events', ['event_type'], unique=False)
    op.create_index(op.f('ix_tracking_events_referral_id'), 'tracking_events', ['referral_id'], unique=False)
    op.create_index(op.f('ix_tracking_events_session_id'), 'tracking_events', ['session_id'], unique=False)
    op.create_table('counsellings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('counsellor_user_id', sa.Integer(), nullable=True),
    sa.Column('scheduled_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('status', sa.Enum('SCHEDULED', 'CONTACTED', 'COMPLETED', 'NO_SHOW', 'RESCHEDULED', 'CANCELLED', name='counsellingstatus', native_enum=False), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('outcome', sa.String(length=200), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['counsellor_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_counsellings_lead_id'), 'counsellings', ['lead_id'], unique=False)
    op.create_index(op.f('ix_counsellings_public_id'), 'counsellings', ['public_id'], unique=True)
    op.create_index(op.f('ix_counsellings_status'), 'counsellings', ['status'], unique=False)
    op.create_table('enrollments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=True),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('campaign_id', sa.Integer(), nullable=True),
    sa.Column('external_reference', sa.String(length=160), nullable=True),
    sa.Column('status', sa.Enum('PENDING', 'CONFIRMED', 'CANCELLED', 'REFUNDED', 'COMPLETED', name='enrollmentstatus', native_enum=False), nullable=False),
    sa.Column('course_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('enrolled_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['campaign_id'], ['campaigns.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('external_reference')
    )
    op.create_index(op.f('ix_enrollments_affiliate_id'), 'enrollments', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_enrollments_campaign_id'), 'enrollments', ['campaign_id'], unique=False)
    op.create_index(op.f('ix_enrollments_course_id'), 'enrollments', ['course_id'], unique=False)
    op.create_index(op.f('ix_enrollments_lead_id'), 'enrollments', ['lead_id'], unique=False)
    op.create_index(op.f('ix_enrollments_public_id'), 'enrollments', ['public_id'], unique=True)
    op.create_index(op.f('ix_enrollments_status'), 'enrollments', ['status'], unique=False)
    op.create_table('commissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('public_id', sa.String(length=36), nullable=False),
    sa.Column('affiliate_id', sa.Integer(), nullable=False),
    sa.Column('lead_id', sa.Integer(), nullable=False),
    sa.Column('enrollment_id', sa.Integer(), nullable=False),
    sa.Column('course_id', sa.Integer(), nullable=False),
    sa.Column('commission_rule_id', sa.Integer(), nullable=True),
    sa.Column('course_price_snapshot', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('percentage_snapshot', sa.Numeric(precision=7, scale=4), nullable=True),
    sa.Column('fixed_amount_snapshot', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('amount', sa.Numeric(precision=12, scale=2), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'UNDER_REVIEW', 'APPROVED', 'REJECTED', 'PAID', 'REVERSED', name='commissionstatus', native_enum=False), nullable=False),
    sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['affiliate_id'], ['affiliates.id'], ),
    sa.ForeignKeyConstraint(['commission_rule_id'], ['commission_rules.id'], ),
    sa.ForeignKeyConstraint(['course_id'], ['courses.id'], ),
    sa.ForeignKeyConstraint(['enrollment_id'], ['enrollments.id'], ),
    sa.ForeignKeyConstraint(['lead_id'], ['leads.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_commissions_affiliate_id'), 'commissions', ['affiliate_id'], unique=False)
    op.create_index(op.f('ix_commissions_course_id'), 'commissions', ['course_id'], unique=False)
    op.create_index(op.f('ix_commissions_enrollment_id'), 'commissions', ['enrollment_id'], unique=True)
    op.create_index(op.f('ix_commissions_lead_id'), 'commissions', ['lead_id'], unique=False)
    op.create_index(op.f('ix_commissions_public_id'), 'commissions', ['public_id'], unique=True)
    op.create_index(op.f('ix_commissions_status'), 'commissions', ['status'], unique=False)
    op.create_table('payout_commissions',
    sa.Column('payout_id', sa.Integer(), nullable=False),
    sa.Column('commission_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['commission_id'], ['commissions.id'], ),
    sa.ForeignKeyConstraint(['payout_id'], ['payouts.id'], ),
    sa.PrimaryKeyConstraint('payout_id', 'commission_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('payout_commissions')
    op.drop_index(op.f('ix_commissions_status'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_public_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_lead_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_enrollment_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_course_id'), table_name='commissions')
    op.drop_index(op.f('ix_commissions_affiliate_id'), table_name='commissions')
    op.drop_table('commissions')
    op.drop_index(op.f('ix_enrollments_status'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_public_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_lead_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_course_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_campaign_id'), table_name='enrollments')
    op.drop_index(op.f('ix_enrollments_affiliate_id'), table_name='enrollments')
    op.drop_table('enrollments')
    op.drop_index(op.f('ix_counsellings_status'), table_name='counsellings')
    op.drop_index(op.f('ix_counsellings_public_id'), table_name='counsellings')
    op.drop_index(op.f('ix_counsellings_lead_id'), table_name='counsellings')
    op.drop_table('counsellings')
    op.drop_index(op.f('ix_tracking_events_session_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_referral_id'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_event_type'), table_name='tracking_events')
    op.drop_index(op.f('ix_tracking_events_affiliate_id'), table_name='tracking_events')
    op.drop_index('ix_tracking_event_type_created', table_name='tracking_events')
    op.drop_table('tracking_events')
    op.drop_index(op.f('ix_leads_status'), table_name='leads')
    op.drop_index(op.f('ix_leads_referral_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_public_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_phone'), table_name='leads')
    op.drop_index(op.f('ix_leads_email'), table_name='leads')
    op.drop_index(op.f('ix_leads_campaign_id'), table_name='leads')
    op.drop_index(op.f('ix_leads_affiliate_id'), table_name='leads')
    op.drop_index('ix_leads_affiliate_created', table_name='leads')
    op.drop_table('leads')
    op.drop_index(op.f('ix_referrals_session_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_public_id'), table_name='referrals')
    op.drop_index('ix_referrals_affiliate_session', table_name='referrals')
    op.drop_index(op.f('ix_referrals_affiliate_link_id'), table_name='referrals')
    op.drop_index(op.f('ix_referrals_affiliate_id'), table_name='referrals')
    op.drop_table('referrals')
    op.drop_index(op.f('ix_performance_events_occurred_at'), table_name='performance_events')
    op.drop_index(op.f('ix_performance_events_event_type'), table_name='performance_events')
    op.drop_index(op.f('ix_performance_events_affiliate_id'), table_name='performance_events')
    op.drop_table('performance_events')
    op.drop_index(op.f('ix_payouts_status'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_public_id'), table_name='payouts')
    op.drop_index(op.f('ix_payouts_affiliate_id'), table_name='payouts')
    op.drop_table('payouts')
    op.drop_index(op.f('ix_affiliate_links_referral_code'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_public_id'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_course_id'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_campaign_id'), table_name='affiliate_links')
    op.drop_index(op.f('ix_affiliate_links_affiliate_id'), table_name='affiliate_links')
    op.drop_table('affiliate_links')
    op.drop_index(op.f('ix_notifications_user_id'), table_name='notifications')
    op.drop_table('notifications')
    op.drop_index(op.f('ix_content_assets_public_id'), table_name='content_assets')
    op.drop_index(op.f('ix_content_assets_campaign_id'), table_name='content_assets')
    op.drop_table('content_assets')
    op.drop_index(op.f('ix_commission_rules_public_id'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_course_id'), table_name='commission_rules')
    op.drop_index(op.f('ix_commission_rules_campaign_id'), table_name='commission_rules')
    op.drop_table('commission_rules')
    op.drop_index(op.f('ix_audit_logs_entity_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_entity_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_affiliates_user_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_status'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_public_id'), table_name='affiliates')
    op.drop_index(op.f('ix_affiliates_affiliate_id'), table_name='affiliates')
    op.drop_table('affiliates')
    op.drop_index(op.f('ix_affiliate_applications_status'), table_name='affiliate_applications')
    op.drop_index(op.f('ix_affiliate_applications_public_id'), table_name='affiliate_applications')
    op.drop_index(op.f('ix_affiliate_applications_phone'), table_name='affiliate_applications')
    op.drop_index(op.f('ix_affiliate_applications_email'), table_name='affiliate_applications')
    op.drop_table('affiliate_applications')
    op.drop_index(op.f('ix_users_role'), table_name='users')
    op.drop_index(op.f('ix_users_public_id'), table_name='users')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_courses_slug'), table_name='courses')
    op.drop_index(op.f('ix_courses_public_id'), table_name='courses')
    op.drop_table('courses')
    op.drop_index(op.f('ix_campaigns_public_id'), table_name='campaigns')
    op.drop_index(op.f('ix_campaigns_code'), table_name='campaigns')
    op.drop_table('campaigns')
    # ### end Alembic commands ###
